"""Initial migration

Revision ID: 179c8dd297f9
Revises: 
Create Date: 2025-04-08 22:12:19.237647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '179c8dd297f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.String(length=10), nullable=False),
    sa.Column('student_name', sa.String(length=150), nullable=False),
    sa.Column('sender_info', sa.String(length=150), nullable=False),
    sa.Column('student_email', sa.String(length=150), nullable=False),
    sa.Column('late_pickup_date', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.alter_column('recipient_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('date_received',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.alter_column('date_received',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('recipient_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    op.drop_table('student')
    op.drop_table('order')
    # ### end Alembic commands ###
